# Generated by Django 3.1.1 on 2020-11-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('author', models.CharField(default='Who did it?', max_length=100)),
                ('title', models.CharField(default='what was it?', max_length=200)),
                ('note', models.TextField()),
                ('week', models.IntegerField(default=1)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
    ]
