# Generated by Django 3.1.1 on 2020-11-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpiece',
            name='authorId',
        ),
        migrations.AddField(
            model_name='contentpiece',
            name='author',
            field=models.CharField(default='Who did it?', max_length=100),
        ),
        migrations.AlterField(
            model_name='contentpiece',
            name='title',
            field=models.CharField(default='what was it?', max_length=200),
        ),
    ]
