# Generated by Django 3.1.1 on 2020-11-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20201120_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpiece',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contentpiece',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
